#ifndef TEST_SUBTITLE_DATA_SERIALIZER_H
#define TEST_SUBTITLE_DATA_SERIALIZER_H


#include <QtTest>
#include <QDebug>
#include <QFile>
#include <QTemporaryFile>
#include <QString>
#include <QStringList>

#include "auto_test.h"
#include "reader/subtitle_data_serializer.h"
#include "reader/subtitle_block.h"
#include "reader/subtitle_row.h"
#include "fixtures/fixture_subtitle.h"


class TestSubtitleDataSerializer: public QObject
{
    Q_OBJECT
public:
    TestSubtitleDataSerializer() = default;
    ~TestSubtitleDataSerializer() = default;

private:
    void fillFileWithData(QFile &file, const QStringList &data);

private slots:
    void TestReadFromFileRaiseExceptionOnReadFail();
    void TestReadFromFile();

private:
    SubtitleDataSerializer serializer;
};

class QFileMocked: public QFile
{
public:
    QFileMocked(const QString &path): QFile(path)
    { }

    bool open(OpenMode flags) override
    {
        Q_UNUSED(flags);
        return false;
    }
};

inline void TestSubtitleDataSerializer::fillFileWithData(QFile &file, const QStringList &data)
{
    if( file.open( QIODevice::WriteOnly | QIODevice::Text) )
    {
        QTextStream out( &file );

        for( const QString &line: data )
        {
            out << line << '\n';
        }

        file.close();
    }
    else
    {
        qCritical() << "Failed to open file!";
    }
}

inline void TestSubtitleDataSerializer::TestReadFromFileRaiseExceptionOnReadFail()
{
    QFileMocked tempFile("tempfile.txt");

    // In a fact there are FileNotOpenedException exception, but somehow i can't catch it :(
    QVERIFY_THROWS_EXCEPTION( std::runtime_error, serializer.readFromFile( tempFile ) );
}

inline void TestSubtitleDataSerializer::TestReadFromFile()
{
    const QStringList &data = regularSubtitleData;

    SubtitleData expectedData{
        QList<SubtitleBlock>{
            SubtitleBlock{
                "Script Info",
                {
                    SubtitleRowPtr( new HeaderSubtitleRow( "[Script Info]" ) ),
                    SubtitleRowPtr( new CommentSubtitleRow( "; Script generated by Aegisub 3.2.2" ) ),
                    SubtitleRowPtr( new ContentSubtitleRow( "ScaledBorderAndShadow: no" ) ),
                    SubtitleRowPtr( new ContentSubtitleRow( "ScriptType: v4.00+" ) ),
                    SubtitleRowPtr( new ContentSubtitleRow( "PlayResX: 640" ) ),
                    SubtitleRowPtr( new EmptySubtitleRow() ),
                    SubtitleRowPtr( new EmptySubtitleRow() ),
                },
            },
            SubtitleBlock{
                "Aegisub Project Garbage",
                {
                    SubtitleRowPtr( new HeaderSubtitleRow( "[Aegisub Project Garbage]" ) ),
                    SubtitleRowPtr( new EmptySubtitleRow() ),
                },
            },
            SubtitleBlock{
                "V4+ Styles",
                {
                    SubtitleRowPtr( new HeaderSubtitleRow( "[V4+ Styles]" ) ),
                    SubtitleRowPtr( new FormatterSubtitleRow( "Format: Name, Fontname, Fontsize, PrimaryColour" ) ),
                    SubtitleRowPtr( new ContentSubtitleRow( "Style: Main,Calibri,42,&H00FFFFFF" ) ),
                    SubtitleRowPtr( new ContentSubtitleRow( "Style: Dialog,Times New Roman,22,&H00FFFFFF" ) ),
                },
            },
            SubtitleBlock{
                "Events",
                {
                    SubtitleRowPtr( new HeaderSubtitleRow( "[Events]" ) ),
                    SubtitleRowPtr( new FormatterSubtitleRow( "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text" ) ),
                    SubtitleRowPtr( new ContentSubtitleRow( "Dialogue: 0,0:02:35.97,0:02:39.04,Main,Lilith,0,0,0,,Main dialog row." ) ),
                    SubtitleRowPtr( new ContentSubtitleRow( "Dialogue: 0,0:02:40.38,0:02:44.20,Dialog,lilith,0,0,0,,Dialog subtitle row." ) ),
                },
            },
        }
    };

    QTemporaryFile file;
    fillFileWithData( file, data );

    SubtitleData result = serializer.readFromFile( file );


    QCOMPARE_EQ(expectedData, result);
}

DECLARE_TEST( TestSubtitleDataSerializer );


#endif // TEST_SUBTITLE_DATA_SERIALIZER_H
