#ifndef FIXTURE_SUBTITLE_H
#define FIXTURE_SUBTITLE_H

#include <QStringList>


static const QStringList regularSubtitleData{
    "[Script Info]",
    "; Script generated by Aegisub 3.2.2",
    "ScaledBorderAndShadow: no",
    "ScriptType: v4.00+",
    "PlayResX: 640",
    "",
    "",
    "[Aegisub Project Garbage]",
    "",
    "[V4+ Styles]",
    "Format: Name, Fontname, Fontsize, PrimaryColour",
    "Style: Main,Calibri,42,&H00FFFFFF",
    "Style: Dialog,Times New Roman,22,&H00FFFFFF",
    "[Events]",
    "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
    "Dialogue: 0,0:02:35.97,0:02:39.04,Main,Lilith,0,0,0,,Main dialog row.",
    "Dialogue: 0,0:02:40.38,0:02:44.20,Dialog,lilith,0,0,0,,Dialog subtitle row.",
};


#endif // FIXTURE_SUBTITLE_H
